
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import light_off_moussally_valentini.Partie;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arthu
 */
public class Form_Main extends javax.swing.JFrame {
    Partie partieEnCours;
    JButton[][] ListeBouton ;
    int nbCoups =0;
    /**
     * Creates new form Form_Main
     */
    public Form_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGrille = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerTailleGrille = new javax.swing.JSpinner();
        jButtonNouvellePartie = new javax.swing.JButton();
        jLabelTailleGrille = new javax.swing.JLabel();
        jLabelTailleGrille1 = new javax.swing.JLabel();
        jTextFieldNBCOUPS = new javax.swing.JTextField();
        jPanelMain = new javax.swing.JPanel();
        InternalFrame = new javax.swing.JInternalFrame();

        jTableGrille.setName("Table_Grille"); // NOI18N
        jTableGrille.setRequestFocusEnabled(false);
        jTableGrille.setRowHeight(30);
        jTableGrille.setRowSelectionAllowed(false);
        jTableGrille.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableGrille.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableGrille.setShowGrid(false);
        jScrollPane1.setViewportView(jTableGrille);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIGHT OFF");

        jSpinnerTailleGrille.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinnerTailleGrillePropertyChange(evt);
            }
        });

        jButtonNouvellePartie.setText("Nouvelle Partie");
        jButtonNouvellePartie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNouvellePartieMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonNouvellePartieMousePressed(evt);
            }
        });

        jLabelTailleGrille.setText("Taille Grille");

        jLabelTailleGrille1.setText("Nombre de Coups");

        jTextFieldNBCOUPS.setEditable(false);
        jTextFieldNBCOUPS.setText("0");
        jTextFieldNBCOUPS.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonNouvellePartie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTailleGrille, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerTailleGrille, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTailleGrille1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNBCOUPS, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 232, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTailleGrille)
                    .addComponent(jSpinnerTailleGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTailleGrille1)
                    .addComponent(jTextFieldNBCOUPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonNouvellePartie))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        InternalFrame.setVisible(true);
        InternalFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(InternalFrame))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNouvellePartieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNouvellePartieMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNouvellePartieMousePressed

    private void jButtonNouvellePartieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNouvellePartieMouseClicked
        // on créée la partie avec le paramétrage demandé
        partieEnCours = new Partie();
        partieEnCours.placerCase((int) jSpinnerTailleGrille.getValue());
        nbCoups = 0;
        jTextFieldNBCOUPS.setText( Integer.toString( nbCoups));
        // on créé les bouttons à l'écran
        ListeBouton = new JButton[(int) jSpinnerTailleGrille.getValue()][(int) jSpinnerTailleGrille.getValue()];
        int i,j;        
        InternalFrame.setLayout(new GridLayout((Integer) jSpinnerTailleGrille.getValue(),(Integer) jSpinnerTailleGrille.getValue()));
        InternalFrame.getContentPane().removeAll();
        InternalFrame.repaint();
        for(i=0;i<(Integer) jSpinnerTailleGrille.getValue();i++)
        {
            for(j=0;j<(Integer) jSpinnerTailleGrille.getValue();j++)
            {
		// Creates button with text 'Test Button'
		JButton button = new JButton("Test Button");
                button.setName("BUTTON"+i+"_"+j);
		button.setSize(30,30);
                //button.addActionListener(this);
                 button.addActionListener(new ActionListener()    {  public void actionPerformed(ActionEvent e) { JButton currentButton = (JButton) e.getSource(); ClicSurBouton(currentButton.getName()); }           });                
		//Creates a container which is going to have various controls like button.. 
		Container container = InternalFrame.getContentPane();
                ListeBouton[i][j] = button;
		// Adding button to container of frame.
		container.add(button);
		InternalFrame.setSize(500,200);
		InternalFrame.setVisible(true);
		//frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
          if (partieEnCours.getPlateau().getCellules()[i][j].est_allume())
          {
            //  jTableGrille.
              button.setText("1");
              button.setBackground(Color.yellow);
 
          }
          else
          {
              button.setText("0");
              button.setBackground(Color.GRAY);
          }
        }
      }
          
          
                 
    }//GEN-LAST:event_jButtonNouvellePartieMouseClicked

    private void jSpinnerTailleGrillePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinnerTailleGrillePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerTailleGrillePropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jSpinnerTailleGrille.setValue(5);
    }//GEN-LAST:event_formWindowOpened

    private void ClicSurBouton(String nombouton)
    {
        
        int pos = nombouton.indexOf('_');
        int i = Integer.parseInt(nombouton.substring(6, pos));
        int j = Integer.parseInt(nombouton.substring(pos+1, nombouton.length()));
        nbCoups++;
        jTextFieldNBCOUPS.setText( Integer.toString( nbCoups));
        partieEnCours.getPlateau().clic(i, j);
        
        MiseAJourAffichage();
    }
    
        
    private void MiseAJourAffichage()
    {
        int i,j;
               
        for(i=0;i<(Integer) jSpinnerTailleGrille.getValue();i++)
        {
            for(j=0;j<(Integer) jSpinnerTailleGrille.getValue();j++)
            {
               if (partieEnCours.getPlateau().getCellules()[i][j].est_allume())
               {
                  //  jTableGrille.
                  ListeBouton[i][j].setText("1");
                  ListeBouton[i][j].setBackground(Color.yellow);
 
                }
                else
                {
                  ListeBouton[i][j].setText("0");
                  ListeBouton[i][j].setBackground(Color.GRAY);
                }
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame InternalFrame;
    private javax.swing.JButton jButtonNouvellePartie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTailleGrille;
    private javax.swing.JLabel jLabelTailleGrille1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerTailleGrille;
    private javax.swing.JTable jTableGrille;
    private javax.swing.JTextField jTextFieldNBCOUPS;
    // End of variables declaration//GEN-END:variables
}
